### ISSUE TITLE
Build Failed Rosetta

### ISSUE THREAD

**Issue by khoogheem** [webex/webex-ios-sdk#166]
Trying to build for simulators brings up build errors when adding in the Webex pod.. 
When trying to build on any simulator device.. I have tried from 15.5 up to 16.4

I have tried back to 3.7.1 and it still provides the same issue.

Xcode 14.3.1

We are running with standard arch

![Screenshot 2023-07-07 at 8 04 40 AM](https://github.com/webex/webex-ios-sdk/assets/957336/47c735f8-65e0-4adb-be2e-f5002281f122)

and yes.. I would rather not have to use Rosetta to build..

**Comment by pumoru** [comment]
Thank you for contacting developer support. Based on the screenshot, it appears to be some kind of Swift Package error. I conducted an online search and found a helpful article that can assist with troubleshooting. https://aptabase.com/blog/how-to-fix-swift-package-missing-architecture Please take a look and let us know if you have any questions.
 
Kind regards,
 
Patience.

**Comment by khoogheem** [comment]
interesting is that the Webex pod is the only one we use that sets excluded archs
