### ISSUE TITLE
Cannot update to Socekt.io 14.0.0

### ISSUE THREAD

**Issue by mughalasim** [webex/webex-ios-sdk#30]
Reason for the update is simply due to the fact that I need to use Socket.io's latest SDK to connect to websockets for other functionality but cannot update it as it uses a version of Starscream that is not compatible with WEBEX SDK.

I'm running Xcode 10.2 and using Swift 4.2

**Pod File**
`pod 'WebexSDK', ~> 2.0.0
  pod 'Socket.IO-Client-Swift', ~> 14.0.0`

**Terminal**
`[!] CocoaPods could not find compatible versions for pod "Starscream:
  In Podfile:
    Socket.IO-Client-Swift (> 14.0.0) was resolved to 14.0.0, which depends on
      Starscream (> 3.0.6)`
`WebexSDK (> 2.0.0) was resolved to 2.0.0, which depends on
      Starscream (= 3.0.5)`

**Comment by MrShiY** [comment]
SDK Starscream is  '~> 4.0.4' now
