### ISSUE TITLE
IOS archiving taking too much time.

### ISSUE THREAD

**Issue by farhanlatheef** [webex/webex-ios-sdk#36]
Since switching from SparkSDK to WebexSDK even though normal build time is ok, while archiving it take too much time. Sometimes over an hour!.

**Comment by farhanlatheef** [comment]
any update on this?.

**Comment by MrShiY** [comment]
@farhanlatheef  what's the result?

**Comment by olivierproffit** [comment]
@farhanlatheef  we are closing the issue since we can't reproduce it. Please let us know if it persists so that they further investigate.
