### ISSUE TITLE
Remove use of UIWebView in the SDK

### ISSUE THREAD

**Issue by aquacode** [webex/webex-ios-sdk#42]
I get deprecated API usage warnings from Apple when I release an IPA to appstoreconnect using the Cisco webex-ios-sdk due to the SDK's usage of UIWebView.
Will this be removed anytime soon?

**Comment by zmeyc** [comment]
@olivierproffit @kliu
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of new apps that use UIWebView APIs starting from April 2020. See https://developer.apple.com/documentation/uikit/uiwebview for more information.

UIWebView seems to be used by Wme.framework which WebexSDK is using.

**Comment by aquacode** [comment]
I believe latest release removed the reference and I would consider this resolved

**Comment by olivierproffit** [comment]
@aquacode @zmeyc we just released the new iOS SDK 2.5 which includes an update of wme.framework that solves that issue. Please let us know if you find any other issue
