### ISSUE TITLE
Enhancement Request for Altering a User's Status and Availability

### ISSUE THREAD

**Issue by BandoKal** [webex/webex-ios-sdk#44]
I have a use-case where I would like the user to be able to alter their own status/availability from a mobile app.

**Comment by krsboone** [comment]
Thank you for submitting your feature request. We opened the request with our product management group - if they elect to implement the new feature, we will announce it on our changelog (https://developer.webex.com/docs/api/changelog) and for larger features, also on our blog (https://developer.webex.com/blog). Please let us know if we can help with anything else.
