### ISSUE TITLE
Initializer for conditional binding must have Optional type

### ISSUE THREAD

**Issue by midhunpmohan** [webex/webex-ios-sdk#46]
getting the following errors after installing webex-ios-sdk
 "Initializer for conditional binding must have Optional type, not 'MembershipReadStatus'"
"Initializer for conditional binding must have Optional type, not 'MembershipReadStatus'"

**Comment by olivierproffit** [comment]
Hi @midhunpmohan we just released the new iOS SDK 2.5. Do you still experience this issue?

**Comment by MrShiY** [comment]
This issue has fixed in release 2.5
