### ISSUE TITLE
WebexSDK with Socket.io

### ISSUE THREAD

**Issue by benshimd** [webex/webex-ios-sdk#48]
Hi, i have a project that needs to use both libraries but when i'm trying to install via cocoa pods i'm getting the following error: 

CocoaPods could not find compatible versions for pod "Starscream":
  In snapshot (Podfile.lock):
    Starscream (= 4.0.0)

  In Podfile:
    Socket.IO-Client-Swift (~> 15.2.0) was resolved to 15.2.0, which depends on
      Starscream (~> 3.1)

    WebexSDK (~> 2.5.0) was resolved to 2.5.0, which depends on
      Starscream (= 4.0.0)

Specs satisfying the `Starscream (= 4.0.0), Starscream (= 4.0.0), Starscream (~> 3.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by MrShiY** [comment]
Hi @benshimd , SDK supports Starscream ~>4.0.4, you must select a version of Socket.IO-Client-Swift which can matches Starscream, Starscream (~> 3.1) is very old，SDK has not supported it.  Alternative, you can replace Socket.IO with  Starscream directly.
