### ISSUE TITLE
Unable to Start Video Call 

### ISSUE THREAD

**Issue by vsp2005** [webex/webex-ios-sdk#56]
I have used the same code provided in the KitchenSink App (Available on Cisco Webex ,Website)
, its not Initiating  call  and also not receiving (H.264 AVC ) alert

**Comment by olivierproffit** [comment]
@vsp2005 have you tried using directly our kitchensink app through testflight (without building it) ?

**Comment by olivierproffit** [comment]
see https://github.com/webex/webex-ios-sdk-example, section "download app"

**Comment by olivierproffit** [comment]
@vsp2005 if your issue still happen you can open a troubleshooting ticket from here: https://developer.webex.com/support
