### ISSUE TITLE
Unable to compile WebexSDK with Xcode 12

### ISSUE THREAD

**Issue by Maor-Mac** [webex/webex-ios-sdk#57]
Build failed when trying to compile the latest release of WebexSDK. The problem is with Starscream framework

![Untitled](https://user-images.githubusercontent.com/68903223/88656247-abad5c00-d0d8-11ea-946e-8e4f038ca320.png)

**Comment by pontusjacobsson** [comment]
A quick fix if you need to get it to work is to fork this repo and change the starscream version in the podspec to `~> 4.0.4`.
Then use your local fork repo in your projects podfile instad.

**Comment by krsboone** [comment]
webex-ios-sdk v2.6 was just released, which includes support for xCode 12.
