### ISSUE TITLE
The Project doesn't build in Xcode 12 with Swift 5.3.

### ISSUE THREAD

**Issue by shyamalschandra** [webex/webex-ios-sdk#64]
I am getting `No such module 'AlamofireObjectMapper'` error right now.  I used the Cocoapod package manager instructions to download but I am getting the following errors in the Package Resolution failure:

`https://github.com/tristanhimmelman/AlamofireObjectMapper has no Package.swift manifest for version 6.3.0`

Could you please contact the appropriate people to fix the packages that are missing from the `webex-ios-sdk`?

Thanks in advance!

**Comment by MrShiY** [comment]
SDK depends on `'AlamofireObjectMapper', '~> 5.1'`  I'm not sure why the error displayed ` version 6.3.0`

**Comment by shyamalschandra** [comment]
Could the developers of the webex SDK please update the code to work with version 6.3.0?

**Comment by EvgeniyGT** [comment]
Any updates here?

**Comment by olivierproffit** [comment]
@shyamalschandra @EvgeniyGT XCode12 support will come in very few days with iOS SDK 2.6 release. Not sure of the Alamofire version we'll support.

**Comment by shyamalschandra** [comment]
@olivierproffit: Please let me know as soon as the support for Xcode 12 is available.  Thank you!

**Comment by EvgeniyGT** [comment]
> @olivierproffit: Please let me know as soon as the support for Xcode 12 is available. Thank you!

Already available

**Comment by olivierproffit** [comment]
@shyamalschandra the new SDK 2.6 supports XCode12 and iOS14

**Comment by shyamalschandra** [comment]
The instructions on the [website](https://developer.webex.com/docs/sdks/ios) are incomplete and the resulting xcworkspace file doesn't build properly with many errors.  Could you please rectify the situation?

I am getting the following errors when I follow the step-by-step (incomplete) instructions on the Cisco website:

![Uploading Screen Shot 2020-10-07 at 6.28.43 AM.png…]()

**Comment by MrShiY** [comment]
@shyamalschandra  have you resolved this issue? I have two solutions to reference.
1.  try `pod update`, if not work, please delete 'Podfile.lock', then pod update.
2. Alternative, change the ` Build Settings -> iOS Deployment Target` of the error dependencies as iOS 9.0.

**Comment by MrShiY** [comment]
Hi @shyamalschandra , I did some changes, can you pull the repo from [the branch](https://github.com/webex/webex-ios-sdk-example/tree/GithubIssues)  to see if it is helpful to you.
