### ISSUE TITLE
App hangs when trying to record a video via UIImagePickerController.

### ISSUE THREAD

**Issue by EvgeniyGT** [webex/webex-ios-sdk#68]
Environment: 
- iOS 14.0.1
- Webex SDK: 2.6.0

```
let pickerController = UIImagePickerController()
pickerController.delegate = self
pickerController.allowsEditing = true
pickerController.mediaTypes = ["public.image", "public.movie"]
pickerController.sourceType = .camera
present(pickerController, animated:true)
```

Problem:
We noticed that app hangs when trying to record a video via UIImagePickerController after Webex SDK initialization. 
We spend some time on debugging and find out that the problem lays in Microphone switching logic.
UIImagePickerController and **MicrophoneSelector** object (from Wme.framework) start "fighting" for Active microphone in a loop. This leads to app hangs.

**Comment by MrShiY** [comment]
@EvgeniyGT  you are in a video session when you record a video, right?

**Comment by EvgeniyGT** [comment]
@MrShiY no. I just initialize Webex SDK and then present UIImagePickerController.

`
import UIKit
import WebexSDK

class ViewController: UIViewController {
    private var webexSDK: Webex?

    override func viewDidLoad() {
        super.viewDidLoad()
        
        setupWebex()
        
        DispatchQueue.main.asyncAfter(deadline: .now() + 5) {
            self.presentPicker()
        }
    }
}

private class WebexEnvirmonment {
    static let clientId = "C416dd36dd57b536a35816978e4f063a98849d285ca191f5566a32c0f0c3481ab"
    static let clientSecret = "bc851e0f4d4bd62c020a45de08e374101910200d43096f32d14b9e08164adac7"
    static let scope = "spark:all"
    static let redirectUri = "KitchenSink://response"
}

private extension ViewController {
    func setupWebex() {
        let authenticator = OAuthAuthenticator(clientId: WebexEnvirmonment.clientId,
                                               clientSecret: WebexEnvirmonment.clientSecret,
                                               scope: WebexEnvirmonment.scope,
                                               redirectUri: WebexEnvirmonment.redirectUri)
        webexSDK = Webex(authenticator: authenticator)
    }
    
    func presentPicker() {
        let pickerController = UIImagePickerController()
        pickerController.mediaTypes = ["public.image", "public.movie"]
        pickerController.sourceType = .camera
        present(pickerController, animated:true)
    }
}
`

You can check my repo: https://github.com/EvgeniyGT/Webex_2.6.0_issue

**Comment by MrShiY** [comment]
@EvgeniyGT  The issue has been fixed in GithubIssues branch, can you have a try?
`pod 'WebexSDK', :git => 'git@github.com:webex/webex-ios-sdk.git', :branch => 'GithubIssues'`

**Comment by EvgeniyGT** [comment]
@MrShiY Thanks. The issue has been fixed
