### ISSUE TITLE
Active speaker detection broken for grouped call.

### ISSUE THREAD

**Issue by EvgeniyGT** [webex/webex-ios-sdk#70]
Environment:

iOS 14.0.1
Webex SDK: 2.6.0

Preconditions:
Grouped call with User A, B, C

`MediaChangedEvent.activeSpeakerChangedEvent` never posting. 
As a result, `isActiveSpeaker` in `CallMembership` object always `false` for each call participant.
Everything working fine in the previous WebexSDK version

For debugging you can check this function inside WebexSDK
`private func onMediaEngineDidActiveSpeakerChange(_ notification: Notification)`

**Comment by MrShiY** [comment]
@EvgeniyGT can you collect logs from previous WebexSDK version you mentioned? thanks！

**Comment by MrShiY** [comment]
The issue has been fixed in GithubIssues branch, can you have a try?
`pod 'WebexSDK', :git => 'git@github.com:webex/webex-ios-sdk.git', :branch => 'GithubIssues'`

**Comment by EvgeniyGT** [comment]
@MrShiY Thanks. The issue has been fixed.
