### ISSUE TITLE
Can't build with Xcode 12 due to new Apple Silicon architecture

### ISSUE THREAD

**Issue by aastlind** [webex/webex-ios-sdk#74]
We have Webex pod included as a dependency in a private pod and since Xcode 12 we can't build a new version of our pod due to architecture issues. Cocoapods build pods in "iphonesimulator, release"-mode and this fails since Xcode 12 has Simulator support for Apple Silicon (arm64) and the computers doesn't support this yet. I've tried to fix this on my own, but it seems like the only solution to this is if your pod has support for this.

Attaching log with xcodebuild error.

`ld: warning: directory not found for option '-F/var/folders/n9/t944kg4x06g8yj3dyxc106mc0000gn/T/CocoaPods-Lint-20201102-70257-1snybfc-PrivatePod/Pods/WebexSDK/Frameworks'
    ld: warning: building for iOS Simulator, but linking in dylib built for iOS, 'Seu.framework'
    ld: warning: building for iOS Simulator, but linking in dylib built for iOS, 'Sbu.framework'
    ld: warning: building for iOS Simulator, but linking in dylib built for iOS, 'Wme.framework'
    ld: warning: Could not find or use auto-linked framework 'Wme'
    ld: warning: Could not find or use auto-linked framework 'Sbu'
    ld: warning: Could not find or use auto-linked framework 'Seu'
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_SecureInputStream", referenced from:
          objc-class-ref in UploadFileOperation.o
      "_OBJC_CLASS_$_KmsKey", referenced from:
          objc-class-ref in MessageClient.o
      "_OBJC_CLASS_$_KmsRequest", referenced from:
          objc-class-ref in MessageClient.o
      "_MediaEngineDidMuteVideoNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidChangeLocalScreenShareViewSizeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_KmsEphemeralKeyRequest", referenced from:
          objc-class-ref in MessageClient.o
      "_OBJC_CLASS_$_BroadcastConnectionServer", referenced from:
          objc-class-ref in MediaSessionWrapper.o
      "_OBJC_CLASS_$_MediaConstraint", referenced from:
          objc-class-ref in MediaSessionWrapper.o
      "_OBJC_CLASS_$_MediaCapabilityConfig", referenced from:
          objc-class-ref in MediaSessionWrapper.o
      "_MediaEngineDidChangeLocalViewSizeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidMuteVideoOutputNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineVideoCSI", referenced from:
          closure #1 () -> () in WebexSDK.MediaSessionObserver.(onMediaEngineDidActiveSpeakerChange in _ABF09BFC4A3831458D2F0A19C55B4BF2)(Foundation.Notification) -> () in MediaSessionObserver.o
          closure #1 () -> () in WebexSDK.MediaSessionObserver.(onMediaEngineDidDidCSIChange in _ABF09BFC4A3831458D2F0A19C55B4BF2)(Foundation.Notification) -> () in MediaSessionObserver.o
      "_MediaEngineDidEncounterErrorNotification", referenced from:
          WebexSDK.MediaEngineObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaEngineObserver.o
      "_MediaEngineDidMuteScreenShareNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_MediaSession", referenced from:
          objc-class-ref in MediaSessionWrapper.o
      "_MediaEngineDidUnMuteScreenShareNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidMuteAudioNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidUnMuteAudioNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidUnMuteAudioOutputNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_KmsEphemeralKeyResponse", referenced from:
          objc-class-ref in MessageClient.o
      "_MediaEngineDidChangeAudioRouteNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidDetectVideoMediaAvailableNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidAvailableMediaChangeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidMuteScreenShareOutputNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidActiveSpeakerChangeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidAuxVideoSizeChangeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidDetectAuxVideoMediaUnavailableNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidDetectAuxVideoMediaAvailableNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidMuteAuxVideoNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidDetectScreenShareMediaAvailableNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidUnMuteScreenShareOutputNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_MediaEngine", referenced from:
          objc-class-ref in MediaEngineWrapper.o
          objc-class-ref in MetricsEngine+Call.o
          objc-class-ref in MetricsEngine.o
          objc-class-ref in Phone.o
          objc-class-ref in Webex.o
      "_OBJC_CLASS_$_NetUtils", referenced from:
          objc-class-ref in InterfaceAddress.o
      "_OBJC_CLASS_$_SecureOutputStream", referenced from:
          objc-class-ref in DownloadFileOperation.o
      "_MediaEngineDidCSIChangeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidChangeRemoteViewSizeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidDetectScreenShareMediaUnavailableNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidChangeScreenShareViewSizeNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidMQENotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineVideoCount", referenced from:
          closure #1 () -> () in WebexSDK.MediaSessionObserver.(onMediaEngineDidAvailableMediaChange in _ABF09BFC4A3831458D2F0A19C55B4BF2)(Foundation.Notification) -> () in MediaSessionObserver.o
      "_MediaEngineDidMuteAudioOutputNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_WmeLogManager", referenced from:
          objc-class-ref in MediaEngineWrapper.o
      "_MediaEngineDidSwitchCamerasNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidUnMuteVideoNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_IFAddress", referenced from:
          objc-class-ref in InterfaceAddress.o
          objc-class-ref in Transforms.o
      "_MediaEngineDidDetectVideoMediaUnavailableNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineDidUnMuteAuxVideoNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_MediaEngineVideoID", referenced from:
          merged closure #1 () -> () in WebexSDK.MediaSessionObserver.(onMediaEngineDidAuxVideoSizeChange in _ABF09BFC4A3831458D2F0A19C55B4BF2)(Foundation.Notification) -> () in MediaSessionObserver.o
          closure #1 () -> () in WebexSDK.MediaSessionObserver.(onMediaEngineDidDidCSIChange in _ABF09BFC4A3831458D2F0A19C55B4BF2)(Foundation.Notification) -> () in MediaSessionObserver.o
      "_OBJC_CLASS_$_CjoseWrapper", referenced from:
          objc-class-ref in ContentModel.o
          objc-class-ref in MessageClient.o
          objc-class-ref in ObjectModel.o
      "_MediaEngineDidUnMuteVideoOutputNotification", referenced from:
          WebexSDK.MediaSessionObserver.notificationMapping() -> [(__C.NSNotificationName, ObjectiveC.Selector)] in MediaSessionObserver.o
      "_OBJC_CLASS_$_SecureContentReference", referenced from:
          objc-class-ref in ContentModel.o
          objc-class-ref in FileModel.o
          objc-class-ref in ImageModel.o
          objc-class-ref in UploadFileOperation.o
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by MrShiY** [comment]
SDK supports arm64 architecture, it looks like something wrong with you project architecture. some suggestions below:
1. if you set VALID_ARCHS = arm64, please remove it from you project.
2. try like this.
![tISvF](https://user-images.githubusercontent.com/16798715/97947451-3ed8ea80-1dc8-11eb-8d17-a0b99ae4a849.png)
3. try to change your architecture.

**Comment by MrShiY** [comment]
Or try like this in you APP
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end

**Comment by MrShiY** [comment]
@aastlind  are these suggestions helpful？

**Comment by aastlind** [comment]
Will try this evening (CET), but isn't it possible for you to compile the bundled frameworks with arm64?

**Comment by MrShiY** [comment]
SDK supports arm64 in real device, I think your error is to run with arm64 in a simulator，SDK doesn't support using arm64 for a simulator, @aastlind

**Comment by aastlind** [comment]
Solved with some modifications, but removing arm64 from VALID_ARCHS in main target and excluding arm64 for "Any iOS Simulator SDK (Release)" in the WebexSDK-pod did the trick! Thank you for your guidance!
